name: CI-CD Pipeline

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  FRONTEND_REPO: frontend
  BACKEND_REPO: backend

jobs:
  deploy:
    name: Build, Push & Deploy
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout code
    - name: Checkout
      uses: actions/checkout@v3

    # 2. Configure AWS
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # 3. Log in to ECR
    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # 4. Build Docker Images
    - name: Build Images
      run: |
        docker build -t frontend ./app/frontend
        docker build -t backend ./app/backend

    # 5. Tag Images
    - name: Tag Images
      run: |
        ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

        docker tag frontend:latest $ACCOUNT_ID.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.FRONTEND_REPO }}:latest
        docker tag backend:latest  $ACCOUNT_ID.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.BACKEND_REPO }}:latest

    # 6. Push Images
    - name: Push Images
      run: |
        ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

        docker push $ACCOUNT_ID.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.FRONTEND_REPO }}:latest
        docker push $ACCOUNT_ID.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.BACKEND_REPO }}:latest

    # 7. Terraform Init
    - name: Terraform Init
      working-directory: terraform
      run: terraform init

    # 8. Terraform Apply (Infra)
    - name: Terraform Apply Infra
      working-directory: terraform
      run: |
        ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

        terraform apply -auto-approve \
          -var="frontend_image=$ACCOUNT_ID.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.FRONTEND_REPO }}:latest" \
          -var="backend_image=$ACCOUNT_ID.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.BACKEND_REPO }}:latest"

    # 9. Terraform Apply (K8s)
    - name: Terraform Apply K8s
      working-directory: terraform
      run: |
        ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

        terraform apply -auto-approve \
          -var="frontend_image=$ACCOUNT_ID.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.FRONTEND_REPO }}:latest" \
          -var="backend_image=$ACCOUNT_ID.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.BACKEND_REPO }}:latest"


     # 9. Replace your Terraform K8s step with Helm release for app deployments  (Better Deployment - k8s deployments as App deployments happen frequently)   
#- name: Update kubeconfig
#  run: |
 #   aws eks update-kubeconfig \
  #    --region $AWS_REGION \
  #    --name my-eks-cluster

#- name: Deploy Frontend
#  run: |
 #   helm upgrade --install frontend ./helm/frontend \
 #     --set image.repository=$ACCOUNT_ID.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.FRONTEND_REPO }} \
  #    --set image.tag=${{ github.sha }}

#- name: Deploy Backend
#  run: |
   # helm upgrade --install backend ./helm/backend \
   #   --set image.repository=$ACCOUNT_ID.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.BACKEND_REPO }} \
   #   --set image.tag=${{ github.sha }}
